# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.0
group=dev.cartframes

# Dependencies
fabric_api_version=0.141.6+1.21.11
cloth_config_version=17.0.144
modmenu_version=17.0.0